name: piemonte-data-scraper

# Schedule the run (UTC time)
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 14-23 * * *'

jobs:
  # Set the job key.
  scrape-data:
    # Name of the Job
    name: Scrape data
    # Set the type of machine to run on
    runs-on: macos-latest

    steps:
      # Check out a copy of this repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Get data
      - name: Get data
        run: |
          python scarica_dati_da_regione_piemonte.py
          python aggrega_dati.py

      # Commit & Push
      - name: Commit a new report
        run: |
          echo "Checking data on: `date`"
          git config --global user.name 'Covid Piemonte Bot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git diff-index --quiet HEAD || git commit -am "Refresh data on: `date`"
          git push
        env:
          TZ: Europe/Rome

      # Update data in the website
      - name: Update data in the website
        run: |
          curl https://marcosegato.altervista.org/covid19piemonte/import.php
